version: '3'
services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db:/var/lib/mysql
    networks:
      - project

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    ports:
      - "9000"
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - project
    depends_on:
      - mariadb

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - website:/var/www/html
    depends_on:
      - wordpress
    networks:
      - project
    restart: always

  ftp:
    build: requirements/bonus/vsftpd
    container_name: ftp
    ports:
      - "21:21"
      - "20:20"
      - "990:990"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/ftp
    networks:
      - project
    depends_on:
      - wordpress
    restart: always

  adminer:
    build: requirements/bonus/adminer
    container_name: adminer
    ports:
      - "9000:9000"
    networks:
    - project
    depends_on:
    - mariadb
    restart: always
    volumes:
    - adminer:/var/www/html/adminer
   
  redis:
    build: requirements/bonus/redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - project
    depends_on:
      - wordpress
    restart: always
  static:
    build: requirements/bonus/static
    container_name: static
    ports: 
      - "8000:8000"
    networks: 
      - project
    depends_on: 
      - nginx
    restart: always
    volumes:
      - static:/var/www/html/pelican
  bot:
    build: requirements/bonus/bot
    container_name: bot
    env_file:
      - .env
    ports:
      - "8443"
    networks:
      - project
    depends_on:
      - nginx
    restart: always


volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: home/zyasuo/data/db
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zyasuo/data/website/wordpress
  website:
    name: website
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zyasuo/data/website
  adminer:
    name: adminer
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zyasuo/data/website/adminer
  static:
    name: static
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/zyasuo/data/website/static
   

networks:
  project:
    driver: bridge
